#!/bin/bash

dest="$HOME/brewupdate.log"
all_formulae="$HOME/brewupdate_formulae.txt"
all_casks="$HOME/brewupdate_casks.txt"
usage="\e[1mbru\e[0m [-h]"
help="An updater script for homebrew.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
Executes the commands: brew update, brew upgrade, brew cleanup, brew doctor
Logs the results to $dest.
"

trap "echo 'Interrupted.' | tee -a $dest; end; exit 1" 2

case $1 in
  -h|--help)
    printf "$help"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
  "")
    ;;
  *)
    echo "Arguments will be ignored."
    ;;
esac

end() {
  printf "END on $(date)\n%s\n" >> $dest "******************************************"  # funny this works
}

start() {
  printf "START on $(date)\n" >> $dest
}

new_formulae() {
  # '.items[].formula'
  curl -s https://formulae.brew.sh/api/analytics/install/365d.json \
    | jq -r '.items[] | select(.count | gsub(",";"") | tonumber >= 10) | .formula' \
    | grep -v / \
    | sort > "$all_formulae.new"
  if [ -f "$all_formulae" ]; then
    comm -13 "$all_formulae" "$all_formulae.new" | while read -r name; do
      if curl -fsI "https://formulae.brew.sh/api/formula/${name}.json" >/dev/null; then
        echo "$name"
      fi
    done
  else
    echo "No previous formulae list found; initializing list."
  fi
  mv "$all_formulae.new" "$all_formulae"
}

new_casks() {
  # '.formulae | keys[]'
  curl -s https://formulae.brew.sh/api/analytics/cask-install/homebrew-cask/365d.json \
  | jq -r '.formulae | to_entries[] | select(.value[0].count | gsub(",";"") | tonumber >= 10) | .key' \
  | grep -v '^font\-' \
    | sort > "$all_casks.new"
  if [ -f "$all_casks" ]; then
    comm -13 "$all_casks" "$all_casks.new"
  else
    echo "No previous casks list found; initializing list."
  fi
  mv "$all_casks.new" "$all_casks"
}

runCmd() {
  title=$(echo "$@" | awk '{print toupper($0)}')
  echo "$title" && "$@" 2>&1 | tee /dev/tty | while IFS= read -r line; do printf "%s: %s\n" "$(date +'%Y-%m-%d %T')" "$line"; done >> "$dest"
}

#test internet connection
waitnet -s || exit 1

start

nver_before=$(nativefier --version)

runCmd new_formulae
runCmd new_casks
runCmd brew update
runCmd brew upgrade --greedy
runCmd brew cleanup
runCmd brew doctor

nver_after=$(nativefier --version)

if [[ $nver_before != $nver_after ]]; then
  echo
  echo "*******************************************************"
  echo "nativefier was updated from $nver_before to $nver_after"
  echo "*******************************************************"
  trash -v "/Applications/Duolingo.app"
  trash -v "/Applications/Graphing Calculator.app"
  trash -v "/Applications/Trading212.app"
  sys_install
fi

# hash mas &>/dev/null && runCmd mas upgrade
# softwareupdate --all --install

end
