#!/bin/bash

dest="$HOME/brewupdate.log"
extendedUpgrade=
usage="\e[1mbru\e[0m [-h|-a]"
help="An updater script for homebrew.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
	\e[1m-a\e[0m	Extended processing.
Executes the commands: brew update, brew upgrade
With argument -a additional commands will be executed:
	brew cask upgrade, brew cleanup, brew doctor, mas upgrade
Logs the results to $dest.
"

trap "echo 'Interrupted.' | tee -a $dest; end; exit 1" 2

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -a)
    extendedUpgrade=true
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
  "")
    ;;
  *)
    echo "Arguments will be ignored."
    ;;
esac

end() {
  printf "END on $(date)\n%s\n" >> $dest "******************************************"
}

start() {
  printf "START on $(date)\n" >> $dest
}

runCmd() {
  title=$(echo "$@" | awk '{print toupper($0)}')
  echo "$title" && "$@" 2>&1 | tee /dev/tty | while IFS= read -r line; do printf "%s: %s\n" "$(date +'%Y-%m-%d %T')" "$line"; done >> "$dest"
}

#test internet connection
waitnet -s || exit 1

start
if [[ -n $extendedUpgrade ]]; then
  echo "*** EXTENDED UPGRADE ***" >> $dest
fi
runCmd brew update
runCmd brew upgrade

if [[ -n $extendedUpgrade ]]; then
  runCmd brew cleanup
  runCmd brew doctor
#  hash mas &>/dev/null && runCmd mas upgrade
fi
end
