#!/bin/bash

usage="Usage: \e[1mchocomp\e[0m \e[4mfile\e[0m"
filename=

die() {
  echo "$*"
  exit 1
}

case $1 in
  -h)
    echo "Compiler from chordpro/chordii files to pdf. Give an \".cho\"-file as argument."
    printf "$usage\n"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" $1
    exit 1
    ;;
  "")
    echo "Please give a chordpro/chordii file to compile."
    exit 1
    ;;
  *)
    if [[ "$1" != *.cho ]]; then
      echo "Please give a chordpro/chordii file to compile."
      exit 1
    fi
    if [[ ! -f "$1" || ! -r "$1" ]]; then
      echo "Please give an existing and readable chordii file to compile."
      exit 1
    fi
    filename=${1%.*}
    ;;
esac


if [[ ! -d pdf ]]; then
  mkdir pdf || die "Failed to create pdf/ dir."
fi

if [[ -n $(which chordpro) ]]; then
  chordpro -o pdf/"$filename".pdf "$filename".cho || die "Fail to print pdf from $filename."
  if [[ -f chordpro_long.json && -n $(which mdls) ]]; then
    open -g pdf/"$filename".pdf && sleep 1
    pagenumber=$(mdls -name kMDItemNumberOfPages pdf/"$filename".pdf  | cut -d " " -f 3)
    if [[ -n $pagenumber && $pagenumber == 2 ]]; then
      echo "Well, that lyrics seems to be a little longer. Let try the json for long lyrics."
      chordpro --config=chordpro_long.json -o pdf/"$filename".pdf "$filename".cho || die "Fail to print pdf from $filename."
      open -g pdf/"$filename".pdf && sleep 1
      pagenumber=$(mdls -name kMDItemNumberOfPages pdf/"$filename".pdf  | cut -d " " -f 3)
      if [[ -n $pagenumber && $pagenumber == 2 ]]; then
        echo "That didn't work. Lyrics seems too long for one page. Reverting to default settings."
        chordpro -o pdf/"$filename".pdf "$filename".cho || die "Fail to print pdf from $filename."
      fi
    fi
  fi
else
  echo "chordpro not found. Trying with chordii..."
  chordii -o "$filename".ps "$filename".cho || die "cho to ps conversion failed."
  pstopdf "$filename".ps pdf/"$filename".pdf || die "ps to pdf conversion failed."
  rm "$filename".ps || die "Could not remove ${filename}.ps"
fi

open pdf/"$filename".pdf|| die "Could not open pdf/${filename}.pdf"
