#!/bin/bash

usage="Usage: \e[1mchocomp\e[0m \e[4mfile\e[0m"
filename=

die() {
  echo "$*"
  exit 1
}

case $1 in
  -h)
    echo "Compiler from chordpro/chordii files to pdf. Give an \".cho\"-file as argument."
    printf "$usage\n"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" $1
    exit 1
    ;;
  "")
    echo "Please give a chordpro/chordii file to compile."
    exit 1
    ;;
  *)
    if [[ "$1" != *.cho ]]; then
      echo "Please give a chordpro/chordii file to compile."
      exit 1
    fi
    if [[ ! -f "$1" || ! -r "$1" ]]; then
      echo "Please give an existing and readable chordii file to compile."
      exit 1
    fi
    filename=${1%.*}
    ;;
esac


if [[ ! -d pdf ]]; then
  mkdir pdf || die "Failed to create pdf/ dir."
fi

if [[ -n $(which chordpro) ]]; then
  chordpro -o pdf/"$filename".pdf "$filename".cho || die "Fail to print pdf from $filename."
else
  echo "chordpro not found. Trying with chordii..."
  chordii -o "$filename".ps "$filename".cho || die "cho to ps conversion failed."
  pstopdf "$filename".ps pdf/"$filename".pdf || die "ps to pdf conversion failed."
  rm "$filename".ps || die "Could not remove ${filename}.ps"
fi

open pdf/"$filename".pdf|| die "Could not open pdf/${filename}.pdf"
