#!/bin/bash

lyrics=
title=
artist=
filename=
forceOverwriting=
useLyrics=
destination=$CHO
usage="Usage: \e[1mchoinit\e[0m -h | [-f] [\e[4mtitle\e[0m] [\e[4martist\e[0m]"
help="Script for initiating an chordii file in interplay with \"lyrics\".
$usage
	\e[1m-h\e[0m	Displays this message and exits.
	\e[1m-f\e[0m	Forces overwriting an already existing file.
	\e[4mtitle\e[0m	Song's title.
	\e[4martist\e[0m	Song's artist.
"

die() {
  echo "$*"
  exit 1
}

while [[ -n $1 ]]; do
  case $1 in
    -h|--help)
      printf "$help"
      exit 0
      ;;
    -f)
      forceOverwriting=true
      ;;
    -*)
      printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
      exit 1
      ;;
    *)
      title=$1
      artist=$2
      break;
      ;;
  esac
  shift
done

extractFromLyrics() {
  res=$(echo "$lyrics" | sed -n 1p)
  if [[ -n "$res" ]]; then
    [[ -z "$artist" ]] && artist=$(echo "$res" | sed 's/ - .*//g')
    [[ -z "$title" ]] && title=$(echo "$res" | sed 's/.* - //g')
    lyrics=$(echo "$lyrics" | sed -n '3,$p')
  else
    lyrics=$(echo "$lyrics" | sed -n '2,$p')
  fi
  #echo "lyrics length: ${#lyrics}"
}

toFilename() {
  echo "$*" | sed "s/'//g" \
  | sed 's/"//g' \
  | sed 's/ \{1,\}/_/g' \
  | sed 's/(.*)//g' \
  | sed 's/\[.*\]//g' \
  | sed 's/ - .*//g' \
  | sed 's/_$//'
}

toAscii() {
  echo "$*" | sed "s/ü/ue/g" | sed "s/Ü/Ue/g" | sed "s/ä/ae/g" | sed "s/Ä/Ae/g" | sed "s/Ö/oe/g" | sed "s/ö/oe/g" | sed "s/ß/ss/g"
}

cd "$destination" || die "cd failed"

# if title is there
if [[ -n "$title" ]]; then
  if [[ -t 0 ]]; then
    read -p "Do you want to search for lyrics? (y/n) [y]: " ans
    case $ans in
    n)
      ;;
    *)
      echo "Grabbing lyrics for \"$title\"..."
      # use title/artist with lyrics
      lyrics=$(lyrics -q "$title" "$artist")
      extractFromLyrics
      ;;
    esac
  fi
fi

# if no lyrics and piped, use as lyrics
if [[ -z "$lyrics" ]]; then
  if [[ ! -t 0 ]]; then
    lyrics=$(cat)

    # if no title, try to extract artist / title
    if [[ -z "$title" ]]; then
      [[ -z "$lyrics" ]] && die "Piped lyrics must not be empty if no title is given."
      extractFromLyrics
      # title is mandatory, but if piped, no interaction is possible
      [[ -z "$title" ]] && die "Couldn't extract title from piped. Did you pipe from lyrics?"
      #echo "lyrics length: ${#lyrics}"
    fi
    if [[ -z "$lyrics" ]]; then
      echo "Grabbing lyrics..."
      # grab from lyrics but skip first line with artist and title
      lyrics=$(lyrics -q "$title" "$artist" | sed -n '3,$p')
    fi
  # no lyrics, no title, not piped
  elif [[ -z "$title" ]]; then
    #use lyrics spotify
    echo "Grabbing lyrics from Spotify..."
    lyrics=$(lyrics -q)
    if [[ -n "$lyrics" ]]; then
      extractFromLyrics
    fi
    if [[ -z "$title" ]]; then
      echo "Counldn't grab lyrics automatically. Please give some infomation."
      # ask artist/title and use them with lyrics --ask
      read -p "Who's the artist? " artist
      while [[ -z $title ]]; do printf "Title cannot be empty. "; read -p "What's the title? " title; done
      read -p "Do you want to search for lyrics? (y/n) [y]: " ans
      case $ans in
      n)
        ;;
      *)
        echo "Grabbing lyrics for \"$title\"..."
        # use title/artist with lyrics
        lyrics=$(lyrics -q "$title" "$artist" | sed -n '3,$p')
        ;;
      esac
      lyrics=$(lyrics -q "$title" "$artist")
    fi
  fi
fi

filename="$(toFilename $title)-$(toFilename $artist).cho"
#echo "filename: $filename"

if [[ -e "$filename" && ! -n $forceOverwriting ]]; then
  [[ ! -t 0 ]] && die "Leadsheet \"$filename\" already exists."

  read -p "Overwrite existing \"$filename\" ? [y/n] [y]: " ans
  case $ans in
  n)
    read -p "Please specify another filename: " filename
    [[ -z "$filename" ]] && die "The filename cannot be empty."
    if [[ "$filename" != *.cho ]]; then filename="$filename.cho"; fi
    [[ -e "$filename " ]] && die "This file (\"$filename\") also exists."
    ;;
  esac
fi

content="{title:$(toAscii $title)}
{st:$(toAscii $artist)}

$lyrics"

echo "$content" > "$filename"
echo "Wrote ${#content} bytes to $PWD/$filename"

mate -l 4 -- "$filename"

[[ ! -t 0 ]] && exit 0
[[ -z $(which chocomp) ]] && die "Chodrii compiler (chocomp) not found!"
read -p "Compile now? (y/n) [y]: " ans
case $ans in
n)
  printf "chocomp \"%s\"" "$filename" | pbcopy 2>&1 > /dev/null && echo "Copied to cilpboard."
  ;;
*)
  chocomp "$filename"
esac
