#!/bin/bash

usage="Usage: \e[1m$(basename $0)\e[0m -h | [\e[4mfile\e[0m]"
default_name="main.tex"
goal=
SHORT=
help="Compiles a tex file. Complies multiple times if a bib file is existent, so that literature section is right. Uses pdflatexmkrc if available.
$usage
	\e[1m-h\e[0m	Display this message and exit.
	\e[1m-s\e[0m	Compile only one time with pdflatex.
	\e[4mfile\e[0m	.tex-file to compile (default: $default_name).
"

function die() {
  mes=$1
  shift
  [[ -n "$mes" ]] && printf "$mes\n" "$@"
  exit 1
}

function cltex() {
  local goal=$1
  [[ -z "$goal" && -e "main.tex" ]] && goal="main.tex"
  if [[ ! -e "$goal" || "$goal" != *.tex ]]; then
    echo "Please give a valid tex file." && return 1
  fi

  local -i removed=0
  local -a tokill=(aux bbl bcf blg dvi fdb_latexmk fls idx ilg ind lof log lot out out.ps run.xml spl toc xcp)
  for postfix in ${tokill[@]}; do
    local file="${goal:0:$((${#goal}-4))}.$postfix"
    [[ -e "$file" ]] && rm -v "$file" && ((removed++))
  done
  echo "$removed files removed"
}

function open_it() {
  if hash open &>/dev/null; then
    open "${1:0:$((${#1}-4))}.pdf" || die "Could not open file: $goal"
  fi
  cltex "$1"
}

while [[ $1 == -* ]]; do
  case $1 in
    -h|--help)
      printf "$help"
      exit 0
      ;;
    -s)
      SHORT=true
      ;;
    --)
      break;
      ;;
    -*)
      die "Wrong argument: %s\n$usage -- See -h for more help." "$1"
      ;;
  esac
  shift
done

goal="${1:-$default_name}"
[[ -n "$2" ]] && multiple=true || multiple=

if ! ls | grep '.bib$' &>/dev/null; then
  SHORT=true
fi

if [[ -r "$PWD/pdflatexmkrc" ]]; then
  latexmk -pdf -r pdflatexmkrc "$goal" || die
  open_it "$goal"
elif [[ -n "$goal" ]]; then
  if [[ ! -r "$goal" ]]; then
    echo "Please give an existing and readable file. See -h for more help."
    exit 1
  fi
  pdflatex "$goal" || die 'First latex compilation run failed'
  if [[ -z $SHORT ]]; then
    if cat "$goal" | grep '^\\printbibliography' >/dev/null; then
      biber "${goal:0:$((${#goal}-4))}"
    else
      bibtex "${goal:0:$((${#goal}-3))}aux"
    fi
    pdflatex "$goal" || die 'Second latex compilation run failed'
    pdflatex "$goal" || die 'Third latex compilation run failed'
  fi
  open_it "$goal"
else
 die "Please give a valid tex file. See -h for more help."
fi
