#!/bin/zsh

cmd=
# link regex does not work because (http:)// gets recognized as file path
case $1 in
  fw)
    f w
    ;;
  o*)
    exists=${1:1}
    if [[ -e "$exists" ]]; then
      open "$exists"
    else
      echo "Did you mean: open $exists"
    fi
    ;;
  greo)
    shift
    grep --color=always "$@"
    ;;
  e*)
    arg=${1:1}
    cmd=e
    ;;
  n*)
    arg=${1:1}
    cmd=n
    ;;
  sn*)
    arg=$(1:2)
    cmd=sn
    ;;
  m*)
    arg=${1:1}
    echo "Rby: m \"$arg\""
    cmd=m
    ;;
  sm*)
    arg=$(1:2)
    cmd=sm
    ;;
  *)
    echo "Sorry, did not found: $*"
    echo "Maybe you can add it to handle if it was a frequent misspelling."
    ;;
esac

if [[ -n "$cmd" ]]; then
  args=($@)
  args[1]=$arg
  if read -q "?Did you mean: $cmd ${args[*]} ? (y/n) [n]: "; then
    echo
    . ~/.profile  # index aliases
    $cmd "${args[@]}"
  fi
fi

