#!/bin/bash

# link regex does not work because (http:)// gets recognized as file path
case $1 in
  fw)
    f w
    ;;
  *)
    echo "Sorry, did not found: $*"
    echo "Maybe you can add it to handle if it was a frequent misspelling."
    ;;
esac
