#!/bin/bash

trise=7
tset=20
minute=5

sleepAndSwitch() {
  if [[ $1 -gt 600 ]]; then
    sleep 600 # sleep max 10 min and update timer (sleep halts on lid close)
  else
    sleep $1
    open /Applications/SwitchDarkAndBright.app/
  fi
  calcTimer
}

calcTimer() {
  timeSunrise=$(date -v${trise}H -v${minute}M -v0S +%s)
  dRise=$(echo "$timeSunrise - $(date +%s)" | bc)
  timeSunset=$(date -v${tset}H -v${minute}M -v0S +%s)
  dSet=$(echo "$timeSunset - $(date +%s)" | bc)

  if [[ $dRise < 0 ]]; then
    timeSunrise=$(date -v${trise}H -v${minute}M -v0S -v+1d +%s)
    dRise=$(echo "$timeSunrise - $(date +%s)" | bc)
    if [[ $dSet < 0 ]]; then
      timeSunset=$(date -v${tset}H -v${minute}M -v0S +%s)
      dSet=$(echo "$timeSunset - $(date +%s)" | bc)
      sleepAndSwitch $dRise
    else
      sleepAndSwitch $dSet
    fi
  else
    sleepAndSwitch $dRise
  fi
}

calcTimer
