#!/bin/bash
usage="Usage: \e[1mdic\e[0m -h | [\e[4mkey\e[0m \e[4m...\e[0m]"
help="Sends \e[4mkey\e[0m as search request to Dictionary.app. No argument will nevertheless open it.
$usage
	\e[1m-h\e[0m	Displays this message and exists.
	\e[4mkey\e[0m	The query keywords.
"

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

open "dict://$*"
