#!/bin/bash

usage="Usage: \e[1mformat\e[0m [-h|-s|\e[4mnumber\e[0m|-a]"
help="Prints formatting codes in a table. With no argument it prints all formatting codes.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
	\e[1m-s\e[0m	Prints only the non-color options.
	\e[4mnumber\e[0m	Prints all numbers to there (1-999).
	\e[1m-a\e[0m	Prints all numbers to 108 (last one).
More infomation: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes
"

formatted="0 1 2 4 5 7 8 $(seq 30 37) $(seq 40 47) $(seq 90 97) $(seq 100 107)"
show() {
  printf "Key\tFormat\tCode\n"
  for cnt in $formatted
    do
      printf "$cnt\t\e["$cnt"mTest\e[0m\t"
      echo "\e["$cnt"m"
  done
  exit 0
}

case $1 in
  "")
    show
    ;;
  -s)
    formatted="0 1 2 4 5 7 8"
    show
    ;;
  [0-9]|[0-9][0-9]|[0-9][0-9][0-9])
    formatted=$(seq 0 $1)
    show
    ;;
  -a)
    formatted=$(seq 0 108)
    show
    ;;
  -h)
    printf "$help"
    exit 0
    ;;
  *)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
esac
