#!/bin/bash

regex='^(https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|]'

output=
whatsapp=
usage="Usage: \e[1m$(basename $0)\e[0m -h | [-o \e[4moutfile\e[0m] [--wa] \e[4mlinks\e[0m \e[4m...\e[0m"
help="Generates a html file which redirects to the given link. If multiple links given, the html provides them.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
	\e[4mlinks\e[0m	A link (or multiple links) where the html should redirect to.
	\e[1m-o\e[0m	Give an output file.
	\e[1m--wa\e[0m	On mobiles, the link will open What's App for sharing.
"

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -o)
    if [[ -z $2 ]]; then
      printf "Please give an output file for the html content with argument -o. See -h for more help."
      exit 1
    fi
    output=$2
    shift 2
    ;;
  --wa)
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

#TODO: if [ ! -t 0 ]; then links="$(cat | grep -v '^$')" fi

if [[ $1 == --wa ]]; then
  whatsapp=true
  shift
fi

if [[ -z $1 ]]; then
  echo "Please give a link to generate a redirecting html from. See -h for more help."
  exit 1
elif [[ -n $1 && -z $2 ]]; then
  link="$1"
  if [[ $link =~ ^www\..* ]]; then
    link="https://$1"
  fi
  if [[ ! $link =~ $regex ]]; then
    echo "Invalid link: $link"
    echo "Please give a full specified, valid link."
    exit 1
  fi
  if [[ -n $whatsapp ]]; then
    link="whatsapp://send?text=$link"
  fi
  echo "<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv=\"refresh\" content=\"0; $link\">
    <title>Link to $link</title>
  </head>
  <body>
    <a href=\"$link\">$link</a>
  </body>
</html>" > ${output:-forwarding.html}
else
	printf "" > ${output:-multiple_links.html}
  content="<!DOCTYPE html>
<html>
  <head>
    <title>Multiple Links</title>
  </head>
  <body style=\"margin: auto;\">
    <ul>
"
  while [[ -n $1 ]]; do
    link="$1"
    if [[ $link =~ ^www\..* ]]; then
      link="https://$1"
    fi
    if [[ ! $link =~ $regex ]]; then
      echo "Invalid link: $link"
      echo "Please give only full specified, valid links."
      exit 1
    fi
    if [[ -n $whatsapp ]]; then
      link="whatsapp://send?text=$link"
    fi
    content+="      <li><a href=\"$link\">$link</a></li>
"
    shift
  done
  content+="    </ul>
  </body>
</html>"
  echo $content >> ${output:-multiple_links.html}
fi
