#!/bin/bash

if [[ ! -d .git ]]; then
  echo "This is not a git repository."
  exit 1
fi

if [[ -z $1 ]]; then
  echo "Please specify a name to grab from gitlog."
  exit 1
fi

if [[ "$2" ]]; then
  multi=1
fi

f_gitcnt() {
  git log --shortstat --author "$1" | grep "files\? changed" | awk '{inserted+=$4; deleted+=$6} END {print "Lines inserted:", inserted, "\t Lines deleted:", deleted}'
}

while [[ "$@" ]]; do
  if [[ $multi ]]; then
    echo "$1:"
  fi
  f_gitcnt "$1"
  shift
done
