#!/bin/bash

obj=""

help='Prints all recent Gronkh videos on YouTube.
Usage: \e[1mgr\e[0m [ -h | -o | \e[4mseries\e[0m ]
	\e[1m-h\e[0m	Displays this message and exists.
	\e[1m-o\e[0m	Opens Gronkhs YouTube-site.
        \e[1m-l\e[0m	Display no links.
	\e[4mseries\e[0m	Filters for special series containing \e[4mseries\e[0m (case insensitive).
'

case "$1" in
  -h)
    printf "$help"
    exit 0
    ;;
  -o)
    open https://www.youtube.com/user/Gronkh/videos
    exit 0
    ;;
  -l)
    noLinks=1
    ;;
  -*)
    printf "Wrong argument. $help"
    exit 1
    ;;
  *)
    obj="$1"
    ;;
esac
src=$(curl -s https://www.youtube.com/user/Gronkh/videos)
if [[ $src ]]; then
  if [[ $noLinks ]]; then
    res=$(echo $src | grep -o 'href="/watch?v=[^"]*">[^<]*' | sed 's/href="[^"]*">//' | sed 's/">/'$'\t''/' | grep "$obj")
  else
    res=$(echo $src | grep -o 'href="/watch?v=[^"]*">[^<]*' | sed 's/href="/https:\/\/www.youtube.com/' | sed 's/">/'$'\t''/' | grep "$obj")
  fi
  res=$(echo "$res" | perl -MHTML::Entities -pe 'decode_entities($_);')
  echo "$res"
else
  echo "No internet connection available."
fi
