#!/bin/bash

usage="\e[1minstall\e[0m [-h]"
help="An install script for computer reset.
$usage
	\e[1m-h\e[0m	Displays this message and exists.
	
Warning: Do NOT put in \$PATH! Leave in place.
"

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  *)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

##########################
### Install
##########################

die() {
  echo "ERROR: $*" >&2
  exit 1
}

#home: .bash_profile .m2/settings.xml .tm_properties .ssh/
#keyboard layout
#install terminal layout
#let user choose layout and restart terminal & install script
#prepare installs:
#install keychains
#wlan login
#install dashboard apps
#install brew
#brew install dropbox
#log in
#open app store for apple id
#install adobe, user must give key
#IntelliJ config folder
#install intelliJ, user must gui install and key
#install microsoft programs
#install brew
#brew cask install
#brew install
#app store
#Thunderbird folder
#IdeaProjects
#other files (documents, pictures, music)
#place minecraft in /Appications
#xcode-select --install ?
#copy power point draft uniwue

##########################
### Manual
##########################

# - notational velocity: ~/Dropbox/Org/Notational/
# - spofity login
# - one note login, ggf Excel, Word, PowerPoint
# - import firefox bookmarks
# - calender login google
# - import newsflow opml
