#!/bin/bash

API_KEY="$(git config --global custom.googleAPI)"

die() {
  echo "$*"
  exit 1
}

origin=$1
destination=$2
if [[ -z $origin ]]; then
  echo "Please specify the origin of your route as first argument."
  exit 1
elif [[ -z $destination ]]; then
   ans=$(curl -GsS "https://maps.google.com/maps/api/geocode/json" --data-urlencode "address=$origin" --data-urlencode "key=$API_KEY");
   node -e 'const ans = JSON.parse(process.argv[1]);
     if (ans.results[0]) {
       let result = ans.results[0]
       console.log(result.formatted_address)
       let location = result.geometry.location;
       console.log("Lat: " + location.lat);
       console.log("Lng: " + location.lng);
     } else if (ans.error_message) {
       console.log(ans.error_message);
     } else {
       console.log(ans)
     }
     ' "$ans"
else
  ans=$(curl -sS "https://maps.googleapis.com/maps/api/directions/json?origin=$origin&destination=$destination&units=metric&language=de&key=$API_KEY" || die "Fetching route failed.");
  if [[ $ans == '<!DOCTYPE html>'* ]]; then
    echo "$ans"
  else
    node -e 'const ans = JSON.parse(process.argv[1]);

    switch (ans.status) {
      case "OK":
        console.log("Entfernung: " + ans.routes[0].legs[0].distance.text + " (" + ans.routes[0].legs[0].duration.text + ")");
        break;
      case "INVALID_REQUEST":
        console.log(ans.error_message);
        break;
      case "ZERO_RESULTS":
        console.log("No route found for your request!");
        break;
      default:
        console.log("Unknown status code: " + ans.status);
        console.log(ans)
    }' "$ans"
  fi
fi
