#!/bin/bash

target=
usage="\e[1mpreinstall\e[0m -h | -t \e[4mdir\e[0m"
help="An preparation script for the install script for computer reset.
$usage
	\e[1m-h\e[0m	Displays this message and exists.
	\e[1m-t\e[0m	Give a target folder where the data should be stored.
"

die() {
  echo "ERROR: $*" >&2
  exit 1
}

####################################################
### Args parsing
####################################################

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -t)
    if [[ -z $2 ]]; then
      printf "Please give a target folder with argument -t. See -h for more help.\n"
      exit 1
    elif [[ ! -e $2 ]]; then
      mkdir -p "$2" || die "Failed to create dir $target. See -h for more help.\n"
    elif [[ ! -w $2 ]]; then
      printf "Please give a writeable target folder with argument -t. See -h for more help.\n"
      exit 1
    elif [[ ! -d $2 ]]; then
      printf "Please give a target folder, not a file, with argument -t. See -h for more help.\n"
      exit 1
    fi
    target=$(cd $(dirname "$2"); pwd)/$(basename "$2")
    ;;
  *)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

if [[ -z $target ]]; then
  printf "Please give a target folder. See -h for more help.\n"
  exit 1
fi

####################################################
### Preparation
####################################################

#copy to target
ctt() {
  while [[ -n $1 ]]; do
    printf "Copying $PWD/$1 "
    printf "($(du -sh "$1" | awk '{print $1}')) ...\n"
    cp -a "$1" "$target/" || die "Copying $1 to $target failed"
    shift
  done
}

# Copy from ~
cd "$HOME" || die "cd to $HOME failed"
ctt .bash_profile .m2/settings.xml .tm_properties .ssh .password-store .gnupg
# - IdeaProjects Documents, Pictures, Music
ctt IdeaProjects Documents Pictures Music

cd "Library"
ctt Thunderbird # - Thunderbird folder
ctt "Keyboard Layouts" # - keyboard layout
ctt IntelliJIdea* # IntelliJ config folder

# - minecraft launcher
cd /Applications
ctt Minecraft


####################################################
### Manual
####################################################
cd "$target"
mkdir manual

#export:
echo "Export and save to $target/manual:"
echo " - Terminal layout" # - Terminal layout Homebrew
echo " - Newsflow OPML" # - Newsflow OPML
echo " - Keychains (mircosoft, wlans)" # - keychain (microsoft, wlans)
echo " - Firefox bookmarks" # - firefox bookmarks
#ensure:
mkdir dashboard
echo "Copy to $target/dashboard" # - Dashboard apps
echo " - eCalc_Scientific.wdgt"
echo " - iStat Pro.wdgt"
echo "Copy to $target/"
echo " - [Adobe Pro Installer]" # - adobe installer

