#!/bin/bash
site="https://www.openthesaurus.de/synonyme/"
openlink=""
usage="Usage: \e[1msyn\e[0m -h | [-l] [\e[4mkey\e[0m \e[4m...\e[0m]"
help="Searchs and prints german synonyms for \e[4mkey\e[0m from http://openthesaurus.de. 
No argument opens the website.
$usage
	\e[1m-h\e[0m	Displays this message and exits.
	\e[1m-l\e[0m	Opens the corresponding website.
	\e[4mkey\e[0m	The word(s), the synonym of which you want to know.
"

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -l)
    openlink=1
    shift
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

if [[ -n "$*" ]]; then
  key="$*"
  key=${key// /+}
  key=${key//ä/ae}
  key=${key//Ä/Ae}
  key=${key//ö/oe}
  key=${key//Ö/Oe}
  key=${key//ü/ue}
  key=${key//Ü/Ue}
  key=${key//ß/ss}
  if [[ $openlink ]]; then
    open "${site}$key"
  else
    # test on wifi connection
    waitnet -s || {
      echo "Try manually to open ${site}$key"
      exit 1
    }

    srcf=$(curl -sS -m 2 "${site}$key")
    [[ -z $srcf ]] && echo "No internet connection available." && exit 1
    ans=$(echo "$srcf" | grep -o -e "Gefundene Synonyme:.*\"/>" | sed -e 's/,\ "\/>/\ /' | recode utf-8..latin1 | perl -MHTML::Entities -pe 'decode_entities($_);' | recode latin1..utf-8)
    [[ -n "$ans" ]] && echo $ans || echo "Keine Synonyme gefunden"
  fi
elif [[ $openlink ]]; then
  echo "Please give a keyword to open the link for. See -h for more help."
  exit 1
else
  open "$site"
fi
