#!/bin/bash

thisdir=$(dirname "$PWD/$BASH_SOURCE")
if [[ ! -e $thisdir ]]; then
  thisdir=$(dirname "$BASH_SOURCE")
fi
usage="\e[1minstall\e[0m [-h]"
help="An install script for computer reset.
$usage
	\e[1m-h\e[0m	Displays this message and exists.
	
Warning: Leave in place!
"

#needed data
trading_icon="$IT/trading212.icns"

brews='agedu
aspell
bash-completion
bash-snippets
brightness
bro
chromedriver
cloc
darksky-weather
diff-pdf
expect
fd
ffmpeg
fortune
geoipupdate
git
go
googler
hexedit
howdoi
libass
lorem
lua@5.1
mas
maven
maven-completion
mplayer
mujs
mysql
nativefier
pass
pdfgrep
pick
pup
recode
shpotify
testdisk
wget
wiki
wine
winetricks
you-get
youtube-dl'

brewcasks='android-file-transfer
android-sdk
android-studio
anki
axure-rp
betterzipql
calibre
disablemonitor
dropbox
firefox
flux
freefilesync
freemind
geogebra
google-chrome
google-earth-pro
intellij-idea
iterm2
java
jwzlyrics
mactex
mpv
notational-velocity
osxfuse
qlimagesize
qlstephen
soundflower
spotify
telegram
texstudio
the-unarchiver
thunderbird
ukelele
xquartz'

case $1 in
  -h)
    printf "$help"
    exit 0
    ;;
  -*)
    printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
    exit 1
    ;;
esac

####################################################
### Install
####################################################

die() {
  echo "ERROR: $*!" >&2
  exit 1
}

c() {
  while [[ -n $1 ]]; do
    origin="$thisdir/$1"
    target="$PWD/$1"
    printf "Copying $origin to $target"
    printf "($(du -sh "$origin" | awk '{print $1}')) ...\n"
    cp -a "$origin" "$target/" || die "Copying $origin to $target failed!"
    shift
  done
}

installWifi() {
  ssid=$1
  passwd=$2
  while [[ -z "$ssid" ]]; do
    read -p "Please enter a SSID to connect to (WPA2 only; s = show all available): " ssid
    if [[ "$ssid" = s ]]; then
      echo "Available networks (WPA2 only):"
      /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s | grep 'WPA2'
    fi
  done
  if [[ -n $(networksetup -listpreferredwirelessnetworks en0 | grep "$ssid") ]]; then
    printf "%s already installed!" "$ssid"
    return;
  fi
  while [[ -z "$password" ]]; do
    read -p "Please enter the password for $ssid: " passwd
  done
  networksetup -addpreferredwirelessnetworkatindex Airport "$ssid" 0 WPA2 "$passwd"
}

waitUser() {
  if [[ -n "$*" ]]; then
    echo "$*"
    sleep 2
  fi
  read -p "Press [Enter] to continue ..." trash
}

#go home first
pushd "$HOME" &> /dev/null || die "cd to $HOME failed!"

####################################################
### Partly automatic part
####################################################

# check, if .bash_profile is installed
if [[ -z "$D" ]]; then
  # if not, install it and the other shit
  c .bash_profile .m2/settings.xml .tm_properties .ssh .password-store .gnupg
  #keyboard layout
  cd "Library" || die "cd to $HOME/Library failed!"
  c "Keyboard Layouts" # - keyboard layout
  
  #install terminal layouts
  open "$thisdir/*.terminal"
  #let user choose layout and restart terminal & install script
  echo "Please close this window now and start this script again with you favourite terminal layout."
  printf "\e[4mHint\e[0m: Just set it to standard layout.\n"
  printf "\e[4mHint2\e[0m: Activate secure text entry.\n"
  printf "\e[4mHint3\e[0m: At this point, you can also switch keyboard layout as desired. "
  waitUser
  exit 0
else
  echo "Skipped preferences installation."
fi

#prepare installs
#install keychains ???

# install internet
ping -t 1 -c 1 google.com 2> /dev/null 1> /dev/null
if [[ $? -ne 0 ]]; then #first time. no internet installed
  echo "Creating internet connection ..."
  networksetup -setairportpower en0 on
  #wlan login
  installWifi AdMiNet #pass not installed yet, so paste password here before running
  #AEG
  printf "Turning Wi-Fi off ..."
  networksetup -setairportpower en0 off
  echo " and on ..."
  networksetup -setairportpower en0 on
  sleep 3
  ping -t 3 -c 1 google.com 2> /dev/null 1> /dev/null
  if [[ $? -ne 0 ]]; then
    echo "Auto connection failed. Please select the network from menu bar."
    echo "This script will continue as soon as an internet connection is found."
    ping -t 3 -c 1 google.com 2> /dev/null 1> /dev/null
    while [[ $? -ne 0 ]]; do
      sleep 1
      ping -t 3 -c 1 google.com 2> /dev/null 1> /dev/null
    done
  fi
else
  echo "Skipped internet installation."
fi

# install dashboard apps
if [[ -d "$thisdir/dashboard" ]]; then
  echo "Installing dashboard apps ..."
  c dashboard
  cd "dashboard"
  for wgt in *; do
    open "$wgt"
    waitUser "Install: $wgt"
  done
  cd ".."
  rm -rf dashboard
else
  echo "Skipped Dashboard apps (no \"dashboard\" directory available at $thisdir)"
fi

# install homebrew
if [[ -z $(which brew) ]]; then
  #install brew
  echo "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || die "Installing brew failed."
  echo "Tapping caskroom ..."
  brew tap caskroom/cask || die "brew tap caskroom/cask failed."
else
  echo "Skipped brew installation."
fi

# install dropbox
if [[ ! -e /Applications/Dropbox.app/ ]]; then
  #brew install dropbox
  echo "Installing Dropbox ..."
  brew cask install dropbox || die "brew cask install dropbox failed!"
  #log in dropbox
  open /Applications/Dropbox.app/
  waitUser "Please log in to dropbox!" #deps in Programmchen now available
else
  echo "Skipped dropbox installation."
fi

#install adobe, contains key?
#install microsoft programs

#open app store for apple id
#xcode-select --install ?

#IntelliJ config folder
#install intelliJ, user must gui install and key

if [[ -e "$trading_icon" ]]; then
  echo "All Dropbox data available already."
else
  echo "$trading_icon"
  while [[ ! -e "$trading_icon" ]]; do
    waitUser "Please wait until all dropbox data is synchonized." #dropbox content synced
  done
fi

####################################################
### Full automatic part (place as much waiting time as possible here)
####################################################

#brew cask install
#brew install

#create WhatsApp and Trading212 app with nativefier
if [[ ! -e "/Applications/WhatsApp Web.app" ]]; then
  nativefier -n "WhatsApp Web" http://web.whatsapp.com/ || die "Creating Whatsapp Web.app failed."
  mv "WhatsApp Web-darwin-x64/WhatsApp Web.app" /Applications/
  rm -rf WhatsApp Web-darwin-x64/
else
  echo "Skipped creation of Whatsapp Web.app with nativefier."
fi

if [[ ! -e "/Applications/Trading212.app" ]]; then
  nativefier -i "$trading_icon" -n "Trading212" 'https://www.trading212.com/' || die "Creating Trading212.app failed."
  mv "Trading212-darwin-x64/Trading212.app" /Applications/
  rm -rf Trading212-darwin-x64/
else
  echo "Skipped creation of Trading212.app with nativefier."
fi

#app store
#Thunderbird folder
#IdeaProjects
#other files (documents, pictures, music)
#place minecraft in /Applications
#copy power point draft uniwue

# install other wifis

####################################################
### Manual part
####################################################

# - notational velocity: ~/Dropbox/Org/Notational/
# - spotify login
# - one note login, ggf Excel, Word, PowerPoint
# - import firefox bookmarks
# - calender login google
# - import newsflow opml
# - os shortcuts
# - install "RZUWsec"

popd &> /dev/null