#!/bin/bash

help='List directories with "\e[1mtree\e[0m" to a particular depth.
Usage: \e[1mtdl\e[0m [-S] \e[4mdepth\e[0m
	\e[1m-S\e[0m	Sort entries by size.
	\e[4mdepth\e[0m	Depth of directories listed (1 to 5; default: 1).
'

grep_it() {
  if [[ $1 =~ -?1 ]]; then
    echo "$dirtree" | grep -e "^.─"
  elif [[ $1 =~ -?2 ]]; then
    echo "$dirtree" | grep -e "^.─"  -e "^.   .─"
  elif [[ $1 =~ -?3 ]]; then
    echo "$dirtree" | grep -e "^.─" -e "^.   .─" -e "^.   .   .─"
  elif [[ $1 =~ -?4 ]]; then
    echo "$dirtree" | grep -e "^.─" -e "^.   .─" -e "^.   .   .─" -e "^.   .   .   .─"
  elif [[ $1 =~ -?5 ]]; then
    echo "$dirtree" | grep -e "^.─" -e "^.   .─" -e "^.   .   .─" -e "^.   .   .   .─" -e "^.   .   .   .   .─"
  fi
}

while [[ -n $1 ]]; do
  case $1 in
    [1-5])
      depth=$1
      ;;
    -[1-5])
      depth=$1;
      ;;
    -S)
      sort=1
      ;;
    -h)
      printf "$help"
      exit 0
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
  shift
done

[[ -z $depth ]] && depth=1
#if [[ -z $depth ]]; then 
#  echo "Please give a number 1-5."
#  exit 1
#fi

if [[ -n $sort ]]; then
  dirtree=$(tree -fapFN --du | grep /$)
  res="$(grep_it $depth)"
  echo "$res" | sed -e 's/[│   ]*.── \[drwxr-xr-x //; s/\]//' | sort -r
else
  dirtree=$(tree -faphFN --du | grep /$)
  res="$(grep_it $depth)"
  echo "$res"
fi
