#!/bin/bash

usage="\e[1mtomp3\e[0m -h | \e[4mfile\e[0m \e[4m...\e[0m"
help="Convert any audio file capable by mplayer to mp3.
$usage
        \e[1m-h\e[0m    Displays this message and exits.
        \e[4mfile\e[0m  Files to convert to mp3.
Depencendies to mplayer and lame.
"

case $1 in
-h|--help)
  printf "$help"
  exit 0
  ;;
-*)
  printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
  exit 1
  ;;
esac

die() {
  echo "$*"
  exit 1
}

if type mplayer &>/dev/null && type lame &>/dev/null; then
  for f in "$@" ; do
    mplayer -noar -novideo -ao pcm:fast "$f" || die "mplayer error on converting: $f"
    filename=$(basename "$f")
    #echo "filename: $filename"
    filename=${filename%.*}
    #echo "filename: $filename"
    [[ -z "$filename" ]] && {
      echo "Conversion failed due to bad file name of [${f}] -> [${filename}]"
      continue;
    }
    [[ ! -f audiodump.wav ]] && {
      echo "mplayer could not extract wav from source"
      continue;
    }
    lame --preset extreme audiodump.wav "${filename}.mp3" || die "lame error on converting: $f"
    rm -f audiodump.wav
  done
else
  echo "mplayer or lame not found"
fi
