#!/bin/bash

usage="\e[1mtomp3\e[0m -h | \e[4mfile\e[0m \e[4m...\e[0m"
help="Convert any audio file capable by mplayer to mp3.
$usage
        \e[1m-h\e[0m    Displays this message and exits.
        \e[4mfile\e[0m  Files to convert to mp3.
Dependencies to mplayer and lame.
"

case $1 in
-h|--help)
  printf "$help"
  exit 0
  ;;
-*)
  printf "Wrong argument: %s\n$usage -- See -h for more help.\n" "$1"
  exit 1
  ;;
esac

die() {
  echo "$*"
  exit 1
}

convertWithMplayer() {
  mplayer -noar -novideo -ao pcm:fast "$1" || die "mplayer error on converting: $1"
  [[ ! -f audiodump.wav ]] && {
    echo "mplayer could not extract wav from source"
    continue;
  }
  lame --preset extreme audiodump.wav "$2" || die "lame error on converting: $1"
  rm -f audiodump.wav
}

convertWithFFmpeg() {
  ffmpeg -loglevel warning -stats -hide_banner -i "$1" -vn -ar 44100 -ac 2 -b:a 192k "$2"
}


if hash mplayer &>/dev/null && hash lame &>/dev/null; then
  converter=convertWithMplayer
elif hash ffmpeg &>/dev/null; then
  converter=convertWithFFmpeg
else
  die "No converter found!"
fi

for f in "$@" ; do
  [[  -d "$f" ]] && {
    echo "Skipped \"$f\" as it is a directory"
    continue;
  }

  filename=$(basename "$f")
  #echo "filename: $filename"
  filename=${filename%.*}
  #echo "filename: $filename"
  [[ -z "$filename" ]] && {
    echo "Conversion failed due to bad file name of [${f}] -> [${filename}]"
    continue;
  }
  goal="${filename}.mp3"

  $converter "$f" "$goal"
done
