#!/bin/bash

shopt -s expand_aliases
source ~/.profile  # index aliases
declare -a yts=($(alias | grep "=\'yt\ " | sed 's/alias //g;s/=.*//g'))

function die() {
  mes=$1
  shift
  printf "$mes\n" "$*"
  exit 1
}

[[ 0 -eq "${#yts}" ]] && die "No matching alias found"

for ((cnt=1; $cnt <= ${#yts}; cnt++)); do
  for idx in "${!yts[@]}"; do #bash only
    echo "$((idx+1)): ${yts[$idx]}"
  done
  ((idx++))

  if [[ $idx -eq 1 ]]; then
    printf "Do you want to search that? (y/n) [y]: "
    read -r ans
    [[ y == $ans ]] && eval "$yts"
  else
    printf "Which one? (1-$idx/q) [$cnt]: ";
    read -r ans
    [[ -z $ans ]] && ans=$cnt
    if [[ $ans =~ ^[0-9]+$ ]]; then
      if [[ 1 -le $ans && $idx -ge $ans ]]; then
        ((ans--))
        eval "${yts[$ans]}"
      else
        die "Out of range: $ans"
      fi
    elif [[ $ans == "q" ]]; then
      exit 0
    else
      exit 1
    fi
  fi
done
